# Generated by Django 4.1.7 on 2023-06-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='en_attente',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
