# Generated by Django 4.1.7 on 2023-06-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_cni_garant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='telephone',
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_mail',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
