# Generated by Django 4.1.7 on 2023-06-07 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0009_delete_verificationcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('identifiant', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('phone_mail', models.CharField(blank=True, max_length=50, null=True)),
                ('cni', models.IntegerField(blank=True, null=True)),
                ('Type_compte', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse', models.CharField(blank=True, max_length=100, null=True)),
                ('profession', models.CharField(blank=True, max_length=50, null=True)),
                ('nom_garant', models.CharField(blank=True, max_length=100, null=True)),
                ('prenom_garant', models.CharField(blank=True, max_length=100, null=True)),
                ('cni_garant', models.IntegerField(blank=True, null=True)),
                ('telephone_garant', models.IntegerField(blank=True, null=True)),
                ('adresse_garant', models.CharField(blank=True, max_length=100, null=True)),
                ('profession_garant', models.CharField(blank=True, max_length=20, null=True)),
                ('ceated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
