# Generated by Django 4.1.7 on 2023-06-08 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_client_inscrit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client_inscrit',
        ),
    ]
