# Generated by Django 4.1.7 on 2023-06-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='clients',
            field=models.ManyToManyField(to='accounts.client'),
        ),
    ]
