# Generated by Django 4.1.7 on 2023-06-13 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_agent_clients'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agent',
        ),
    ]
