# Generated by Django 4.2.2 on 2023-06-16 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_payement', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_payement', models.DateField(blank=True, null=True)),
                ('nbr_jours', models.IntegerField(blank=True, null=True)),
                ('jours_restant', models.IntegerField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.agent')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.client')),
            ],
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_type_compte', models.CharField(blank=True, max_length=50, null=True)),
                ('solde_payement', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_payement', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.client')),
            ],
        ),
    ]
