# Generated by Django 4.2.2 on 2023-06-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_payement_jours_restant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payement',
            name='jours_restant',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
