# Generated by Django 4.2.2 on 2023-06-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_payement_jours_restant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payement',
            name='date_payement',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
