# Generated by Django 4.2.2 on 2023-06-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_payement_date_payement'),
    ]

    operations = [
        migrations.AddField(
            model_name='payement',
            name='debut',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payement',
            name='fin',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
