# Generated by Django 4.2.2 on 2023-06-17 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_payement_montant_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payement',
            name='date_payement',
            field=models.DateField(blank=True, null=True),
        ),
    ]
