# Generated by Django 4.2.2 on 2023-06-17 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_payement_date_payement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='date_payement',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='payement',
            name='date_payement',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
