# Generated by Django 4.1.7 on 2023-06-13 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_delete_agent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('controle', '0002_alter_userprofile_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('identifiant', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('adresse', models.CharField(blank=True, max_length=100, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('Telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('Zone', models.CharField(blank=True, max_length=50, null=True)),
                ('cni', models.IntegerField(blank=True, null=True)),
                ('clients', models.ManyToManyField(blank=True, null=True, to='accounts.client')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
