# Generated by Django 4.1.7 on 2023-06-13 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0003_agent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agent',
        ),
    ]
